apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: products-k8s
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30090
        hostPort: 18080
        protocol: TCP